export const mainFeaturedHostelsData = [
  {
    hostelTitle: "Girls Hostel Jamshoro",
    distanceText: "Hostel 7kms away from university of sindh",
    wifiText: "Wifi",
    waterText: "Water",
    electricityText: "Electricity",
    rating: "8.5",
    reviewCount: "134",
    price: "12000",
  },
  {
    hostelTitle: "Girls Hostel Jamshoro",
    distanceText: "Hostel 7kms away from university of sindh",
    wifiText: "Wifi",
    waterText: "Water",
    electricityText: "Electricity",
    rating: "8.5",
    reviewCount: "134",
    price: "12000",
  },
  {
    hostelTitle: "Girls Hostel Jamshoro",
    distanceText: "Hostel 7kms away from university of sindh",
    wifiText: "Wifi",
    waterText: "Water",
    electricityText: "Electricity",
    rating: "8.5",
    reviewCount: "134",
    price: "12000",
  },
  {
    hostelTitle: "Girls Hostel Jamshoro",
    distanceText: "Hostel 7kms away from university of sindh",
    wifiText: "Wifi",
    waterText: "Water",
    electricityText: "Electricity",
    rating: "8.5",
    reviewCount: "134",
    price: "12000",
  },
  {
    hostelTitle: "Girls Hostel Jamshoro",
    distanceText: "Hostel 7kms away from university of sindh",
    wifiText: "Wifi",
    waterText: "Water",
    electricityText: "Electricity",
    rating: "8.5",
    reviewCount: "134",
    price: "12000",
  },
];
